### PR TITLE
Fixing isochrone issues

### LINKED ISSUE #10: Add photometry synthesis

### PR DESCRIPTION
**Pull request by AlexaVillaume**
Hey @ConnorStoneAstro, 

There were some fairly significant bugs with both the creation of the isochrone grid and then selecting isochrones. Take a look at the changes I made in both get_isochrones.py and MIST_isochrones.py. From the testing I've done thus far it seems like I fixed these issues but since you wrote those parts definitely take a look and check if what I've done makes sens to you. In the meantime, I'm going to think about how to make the code more robust with either unit tests or better checks within the code itself.

### CODE REVIEW

**Comment by ConnorStoneAstro** [comment]
I've created a new repo "light-house-analyses" where we can put jupyter notebooks. That way they wont interfere with the PRs here on the main repo. Could you move the notebooks over?

**Comment by AlexaVillaume** [comment]
> I've created a new repo "light-house-analyses" where we can put jupyter notebooks. That way they wont interfere with the PRs here on the main repo. Could you move the notebooks over?

That's a good idea! Yeah, let me work on moving everything over

**Comment by AlexaVillaume** [comment]
Where is the "light-house-analyses" repo @ConnorStoneAstro ?

**Comment by ConnorStoneAstro** [comment]
> Where is the "light-house-analyses" repo @ConnorStoneAstro ?

I sent you an invitation to join the repo. Let me know if it doesn't show up in your inbox

**Comment by AlexaVillaume** [comment]
Got it! Thanks!

**Pull request closed without merging**
